package me.bandu.talk.android.phone.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMMENT".
 */
public class Comment {

    private long id;
    /** Not-null value. */
    private String comment;
    /** Not-null value. */
    private String name;
    private String value1;
    private Integer value2;

    public Comment() {
    }

    public Comment(long id) {
        this.id = id;
    }

    public Comment(long id, String comment, String name, String value1, Integer value2) {
        this.id = id;
        this.comment = comment;
        this.name = name;
        this.value1 = value1;
        this.value2 = value2;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getComment() {
        return comment;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getValue1() {
        return value1;
    }

    public void setValue1(String value1) {
        this.value1 = value1;
    }

    public Integer getValue2() {
        return value2;
    }

    public void setValue2(Integer value2) {
        this.value2 = value2;
    }

}
