package me.bandu.talk.android.phone.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeWorkDaoConfig;
    private final DaoConfig quizDaoConfig;
    private final DaoConfig sentenceDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig workQuizeDaoConfig;

    private final HomeWorkDao homeWorkDao;
    private final QuizDao quizDao;
    private final SentenceDao sentenceDao;
    private final CommentDao commentDao;
    private final WorkQuizeDao workQuizeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeWorkDaoConfig = daoConfigMap.get(HomeWorkDao.class).clone();
        homeWorkDaoConfig.initIdentityScope(type);

        quizDaoConfig = daoConfigMap.get(QuizDao.class).clone();
        quizDaoConfig.initIdentityScope(type);

        sentenceDaoConfig = daoConfigMap.get(SentenceDao.class).clone();
        sentenceDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        workQuizeDaoConfig = daoConfigMap.get(WorkQuizeDao.class).clone();
        workQuizeDaoConfig.initIdentityScope(type);

        homeWorkDao = new HomeWorkDao(homeWorkDaoConfig, this);
        quizDao = new QuizDao(quizDaoConfig, this);
        sentenceDao = new SentenceDao(sentenceDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        workQuizeDao = new WorkQuizeDao(workQuizeDaoConfig, this);

        registerDao(HomeWork.class, homeWorkDao);
        registerDao(Quiz.class, quizDao);
        registerDao(Sentence.class, sentenceDao);
        registerDao(Comment.class, commentDao);
        registerDao(WorkQuize.class, workQuizeDao);
    }
    
    public void clear() {
        homeWorkDaoConfig.getIdentityScope().clear();
        quizDaoConfig.getIdentityScope().clear();
        sentenceDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        workQuizeDaoConfig.getIdentityScope().clear();
    }

    public HomeWorkDao getHomeWorkDao() {
        return homeWorkDao;
    }

    public QuizDao getQuizDao() {
        return quizDao;
    }

    public SentenceDao getSentenceDao() {
        return sentenceDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public WorkQuizeDao getWorkQuizeDao() {
        return workQuizeDao;
    }

}
