package me.bandu.talk.android.phone.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HOME_WORK".
 */
public class HomeWork {

    private long stu_job_id;
    private Integer job_id;
    private String job_status;
    private String stu_job_status;
    private String title;
    private String cdate;
    private String cday;
    private Long deadline;
    private Integer percent;
    private Boolean isfirst;

    public HomeWork() {
    }

    public HomeWork(long stu_job_id) {
        this.stu_job_id = stu_job_id;
    }

    public HomeWork(long stu_job_id, Integer job_id, String job_status, String stu_job_status, String title, String cdate, String cday, Long deadline, Integer percent, Boolean isfirst) {
        this.stu_job_id = stu_job_id;
        this.job_id = job_id;
        this.job_status = job_status;
        this.stu_job_status = stu_job_status;
        this.title = title;
        this.cdate = cdate;
        this.cday = cday;
        this.deadline = deadline;
        this.percent = percent;
        this.isfirst = isfirst;
    }

    public long getStu_job_id() {
        return stu_job_id;
    }

    public void setStu_job_id(long stu_job_id) {
        this.stu_job_id = stu_job_id;
    }

    public Integer getJob_id() {
        return job_id;
    }

    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }

    public String getJob_status() {
        return job_status;
    }

    public void setJob_status(String job_status) {
        this.job_status = job_status;
    }

    public String getStu_job_status() {
        return stu_job_status;
    }

    public void setStu_job_status(String stu_job_status) {
        this.stu_job_status = stu_job_status;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCdate() {
        return cdate;
    }

    public void setCdate(String cdate) {
        this.cdate = cdate;
    }

    public String getCday() {
        return cday;
    }

    public void setCday(String cday) {
        this.cday = cday;
    }

    public Long getDeadline() {
        return deadline;
    }

    public void setDeadline(Long deadline) {
        this.deadline = deadline;
    }

    public Integer getPercent() {
        return percent;
    }

    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    public Boolean getIsfirst() {
        return isfirst;
    }

    public void setIsfirst(Boolean isfirst) {
        this.isfirst = isfirst;
    }

}
