package me.bandu.talk.android.phone.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUIZ".
 */
public class Quiz {

    private long quiz_id;
    private Integer score;//
    private Long stu_job_id;//
    private String title;//
    private String description;//
    private String quiz_type;//
    private Integer level;//
    private String commit_time;//
    private String spend_time;//
    private String quiz_name;//
    private Integer read_quiz_id;//
    private Integer read_times;//
    private Integer read_count;//
    private Integer repeat_quiz_id;//
    private Integer repeat_times;//
    private Integer repeat_count;//
    private Integer recite_quiz_id;//
    private Integer recite_times;//
    private Integer recite_count;//
    private String upload_spend_time;//
    private boolean readingIsDone;
    private boolean reciteIsDone;
    private boolean repeatIsDone;

    public Quiz() {
    }

    public Quiz(long quiz_id) {
        this.quiz_id = quiz_id;
    }

    public Quiz(long quiz_id, Integer score, Long stu_job_id, String title, String description, Integer level, String commit_time, String spend_time, String quiz_name, Integer read_quiz_id, Integer read_times, Integer read_count, Integer repeat_quiz_id, Integer repeat_times, Integer repeat_count, Integer recite_quiz_id, Integer recite_times, Integer recite_count, String upload_spend_time,boolean readingIsDone,boolean reciteIsDone,boolean repeatIsDone) {
        this.quiz_id = quiz_id;
        this.score = score;
        this.stu_job_id = stu_job_id;
        this.title = title;
        this.description = description;
        this.level = level;
        this.commit_time = commit_time;
        this.spend_time = spend_time;
        this.quiz_name = quiz_name;
        this.read_quiz_id = read_quiz_id;
        this.read_times = read_times;
        this.read_count = read_count;
        this.repeat_quiz_id = repeat_quiz_id;
        this.repeat_times = repeat_times;
        this.repeat_count = repeat_count;
        this.recite_quiz_id = recite_quiz_id;
        this.recite_times = recite_times;
        this.recite_count = recite_count;
        this.upload_spend_time = upload_spend_time;
        this.readingIsDone = readingIsDone;
        this.reciteIsDone = reciteIsDone;
        this.repeatIsDone = repeatIsDone;
    }

    public String getQuiz_type() {
        return quiz_type;
    }

    public void setQuiz_type(String quiz_type) {
        this.quiz_type = quiz_type;
    }

    public long getQuiz_id() {
        return quiz_id;
    }

    public void setQuiz_id(long quiz_id) {
        this.quiz_id = quiz_id;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Long getStu_job_id() {
        return stu_job_id;
    }

    public void setStu_job_id(Long stu_job_id) {
        this.stu_job_id = stu_job_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getCommit_time() {
        return commit_time;
    }

    public void setCommit_time(String commit_time) {
        this.commit_time = commit_time;
    }

    public String getSpend_time() {
        return spend_time;
    }

    public void setSpend_time(String spend_time) {
        this.spend_time = spend_time;
    }

    public String getQuiz_name() {
        return quiz_name;
    }

    public void setQuiz_name(String quiz_name) {
        this.quiz_name = quiz_name;
    }

    public Integer getRead_quiz_id() {
        return read_quiz_id;
    }

    public void setRead_quiz_id(Integer read_quiz_id) {
        this.read_quiz_id = read_quiz_id;
    }

    public Integer getRead_times() {
        return read_times;
    }

    public void setRead_times(Integer read_times) {
        this.read_times = read_times;
    }

    public Integer getRead_count() {
        return read_count;
    }

    public void setRead_count(Integer read_count) {
        this.read_count = read_count;
    }

    public Integer getRepeat_quiz_id() {
        return repeat_quiz_id;
    }

    public void setRepeat_quiz_id(Integer repeat_quiz_id) {
        this.repeat_quiz_id = repeat_quiz_id;
    }

    public Integer getRepeat_times() {
        return repeat_times;
    }

    public void setRepeat_times(Integer repeat_times) {
        this.repeat_times = repeat_times;
    }

    public Integer getRepeat_count() {
        return repeat_count;
    }

    public void setRepeat_count(Integer repeat_count) {
        this.repeat_count = repeat_count;
    }

    public Integer getRecite_quiz_id() {
        return recite_quiz_id;
    }

    public void setRecite_quiz_id(Integer recite_quiz_id) {
        this.recite_quiz_id = recite_quiz_id;
    }

    public Integer getRecite_times() {
        return recite_times;
    }

    public void setRecite_times(Integer recite_times) {
        this.recite_times = recite_times;
    }

    public Integer getRecite_count() {
        return recite_count;
    }

    public void setRecite_count(Integer recite_count) {
        this.recite_count = recite_count;
    }

    public String getUpload_spend_time() {
        return upload_spend_time;
    }

    public void setUpload_spend_time(String upload_spend_time) {
        this.upload_spend_time = upload_spend_time;
    }

    public boolean isReadingIsDone() {
        return readingIsDone;
    }

    public void setReadingIsDone(boolean readingIsDone) {
        this.readingIsDone = readingIsDone;
    }

    public boolean isReciteIsDone() {
        return reciteIsDone;
    }

    public void setReciteIsDone(boolean reciteIsDone) {
        this.reciteIsDone = reciteIsDone;
    }

    public boolean isRepeatIsDone() {
        return repeatIsDone;
    }

    public void setRepeatIsDone(boolean repeatIsDone) {
        this.repeatIsDone = repeatIsDone;
    }

}
