package me.bandu.talk.android.phone.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SENTENCE".
 */
public class Sentence {

    private long id;
    private Long sentence_id;
    private Long hw_quiz_id;
    private Long stu_job_id;
    private Long quiz_id;
    private String en;
    private String mp3;
    private Boolean stu_done;
    private String stu_mp3;
    private String stu_score;
    private String current_mp3;
    private Integer current_score;
    private String current_words_score;
    private String words_score;
    private Integer stu_seconds;
    private Integer current_stu_seconds;
    private String mp3_url;

    public Sentence() {
    }

    public Sentence(long id) {
        this.id = id;
    }

    public Sentence(long id, Long sentence_id, Long hw_quiz_id, Long stu_job_id, Long quiz_id, String en, String mp3, Boolean stu_done, String stu_mp3, String stu_score, String current_mp3, Integer current_score, String current_words_score, String words_score, Integer stu_seconds, Integer current_stu_seconds, String mp3_url) {
        this.id = id;
        this.sentence_id = sentence_id;
        this.hw_quiz_id = hw_quiz_id;
        this.stu_job_id = stu_job_id;
        this.quiz_id = quiz_id;
        this.en = en;
        this.mp3 = mp3;
        this.stu_done = stu_done;
        this.stu_mp3 = stu_mp3;
        this.stu_score = stu_score;
        this.current_mp3 = current_mp3;
        this.current_score = current_score;
        this.current_words_score = current_words_score;
        this.words_score = words_score;
        this.stu_seconds = stu_seconds;
        this.current_stu_seconds = current_stu_seconds;
        this.mp3_url = mp3_url;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getSentence_id() {
        return sentence_id;
    }

    public void setSentence_id(Long sentence_id) {
        this.sentence_id = sentence_id;
    }

    public Long getHw_quiz_id() {
        return hw_quiz_id;
    }

    public void setHw_quiz_id(Long hw_quiz_id) {
        this.hw_quiz_id = hw_quiz_id;
    }

    public Long getStu_job_id() {
        return stu_job_id;
    }

    public void setStu_job_id(Long stu_job_id) {
        this.stu_job_id = stu_job_id;
    }

    public Long getQuiz_id() {
        return quiz_id;
    }

    public void setQuiz_id(Long quiz_id) {
        this.quiz_id = quiz_id;
    }

    public String getEn() {
        return en;
    }

    public void setEn(String en) {
        this.en = en;
    }

    public String getMp3() {
        return mp3;
    }

    public void setMp3(String mp3) {
        this.mp3 = mp3;
    }

    public Boolean getStu_done() {
        return stu_done;
    }

    public void setStu_done(Boolean stu_done) {
        this.stu_done = stu_done;
    }

    public String getStu_mp3() {
        return stu_mp3;
    }

    public void setStu_mp3(String stu_mp3) {
        this.stu_mp3 = stu_mp3;
    }

    public String getStu_score() {
        return stu_score;
    }

    public void setStu_score(String stu_score) {
        this.stu_score = stu_score;
    }

    public String getCurrent_mp3() {
        return current_mp3;
    }

    public void setCurrent_mp3(String current_mp3) {
        this.current_mp3 = current_mp3;
    }

    public Integer getCurrent_score() {
        return current_score;
    }

    public void setCurrent_score(Integer current_score) {
        this.current_score = current_score;
    }

    public String getCurrent_words_score() {
        return current_words_score;
    }

    public void setCurrent_words_score(String current_words_score) {
        this.current_words_score = current_words_score;
    }

    public String getWords_score() {
        return words_score;
    }

    public void setWords_score(String words_score) {
        this.words_score = words_score;
    }

    public Integer getStu_seconds() {
        return stu_seconds;
    }

    public void setStu_seconds(Integer stu_seconds) {
        this.stu_seconds = stu_seconds;
    }

    public Integer getCurrent_stu_seconds() {
        return current_stu_seconds;
    }

    public void setCurrent_stu_seconds(Integer current_stu_seconds) {
        this.current_stu_seconds = current_stu_seconds;
    }

    public String getMp3_url() {
        return mp3_url;
    }

    public void setMp3_url(String mp3_url) {
        this.mp3_url = mp3_url;
    }

}
