package me.bandu.talk.android.phone.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOWNLOAD_BEAN".
 */
public class DownloadBean {

    private Long download_id;
    private String download_name;
    private Integer download_state;
    private Integer download_progress;
    private String download_message;
    private Integer download_subject;
    private Integer download_category;

    public DownloadBean() {
    }

    public DownloadBean(Long download_id) {
        this.download_id = download_id;
    }

    public DownloadBean(Long download_id, String download_name, Integer download_state, Integer download_progress, String download_message, Integer download_subject, Integer download_category) {
        this.download_id = download_id;
        this.download_name = download_name;
        this.download_state = download_state;
        this.download_progress = download_progress;
        this.download_message = download_message;
        this.download_subject = download_subject;
        this.download_category = download_category;
    }

    public Long getDownload_id() {
        return download_id;
    }

    public void setDownload_id(Long download_id) {
        this.download_id = download_id;
    }

    public String getDownload_name() {
        return download_name;
    }

    public void setDownload_name(String download_name) {
        this.download_name = download_name;
    }

    public Integer getDownload_state() {
        return download_state;
    }

    public void setDownload_state(Integer download_state) {
        this.download_state = download_state;
    }

    public Integer getDownload_progress() {
        return download_progress;
    }

    public void setDownload_progress(Integer download_progress) {
        this.download_progress = download_progress;
    }

    public String getDownload_message() {
        return download_message;
    }

    public void setDownload_message(String download_message) {
        this.download_message = download_message;
    }

    public Integer getDownload_subject() {
        return download_subject;
    }

    public void setDownload_subject(Integer download_subject) {
        this.download_subject = download_subject;
    }

    public Integer getDownload_category() {
        return download_category;
    }

    public void setDownload_category(Integer download_category) {
        this.download_category = download_category;
    }

}
