package me.bandu.talk.android.phone.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "UNIT_BEAN".
 */
public class UnitBean {

    private Long unit_id;
    private String unit_name;
    private Integer textbook_id;
    private String textbook_name;
    private Integer textbook_subject;
    private Long insert_time;
    private Integer category;

    public UnitBean() {
    }

    public UnitBean(Long unit_id) {
        this.unit_id = unit_id;
    }

    public UnitBean(Long unit_id, String unit_name, Integer textbook_id, String textbook_name, Integer textbook_subject, Long insert_time, Integer category) {
        this.unit_id = unit_id;
        this.unit_name = unit_name;
        this.textbook_id = textbook_id;
        this.textbook_name = textbook_name;
        this.textbook_subject = textbook_subject;
        this.insert_time = insert_time;
        this.category = category;
    }

    public Long getUnit_id() {
        return unit_id;
    }

    public void setUnit_id(Long unit_id) {
        this.unit_id = unit_id;
    }

    public String getUnit_name() {
        return unit_name;
    }

    public void setUnit_name(String unit_name) {
        this.unit_name = unit_name;
    }

    public Integer getTextbook_id() {
        return textbook_id;
    }

    public void setTextbook_id(Integer textbook_id) {
        this.textbook_id = textbook_id;
    }

    public String getTextbook_name() {
        return textbook_name;
    }

    public void setTextbook_name(String textbook_name) {
        this.textbook_name = textbook_name;
    }

    public Integer getTextbook_subject() {
        return textbook_subject;
    }

    public void setTextbook_subject(Integer textbook_subject) {
        this.textbook_subject = textbook_subject;
    }

    public Long getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(Long insert_time) {
        this.insert_time = insert_time;
    }

    public Integer getCategory() {
        return category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

}
