package me.bandu.talk.android.phone.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import me.bandu.talk.android.phone.db.bean.UnitBean;

import me.bandu.talk.android.phone.db.bean.LessonBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LESSON_BEAN".
*/
public class LessonBeanDao extends AbstractDao<LessonBean, Long> {

    public static final String TABLENAME = "LESSON_BEAN";

    /**
     * Properties of entity LessonBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Lesson_id = new Property(0, Long.class, "lesson_id", true, "LESSON_ID");
        public final static Property Lesson_name = new Property(1, String.class, "lesson_name", false, "LESSON_NAME");
        public final static Property Unit_id = new Property(2, Long.class, "unit_id", false, "UNIT_ID");
        public final static Property Isadd = new Property(3, Boolean.class, "isadd", false, "ISADD");
    };

    private DaoSession daoSession;


    public LessonBeanDao(DaoConfig config) {
        super(config);
    }
    
    public LessonBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LESSON_BEAN\" (" + //
                "\"LESSON_ID\" INTEGER PRIMARY KEY ," + // 0: lesson_id
                "\"LESSON_NAME\" TEXT," + // 1: lesson_name
                "\"UNIT_ID\" INTEGER," + // 2: unit_id
                "\"ISADD\" INTEGER);"); // 3: isadd
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_LESSON_BEAN_LESSON_ID ON LESSON_BEAN" +
                " (\"LESSON_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LESSON_BEAN\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LessonBean entity) {
        stmt.clearBindings();
 
        Long lesson_id = entity.getLesson_id();
        if (lesson_id != null) {
            stmt.bindLong(1, lesson_id);
        }
 
        String lesson_name = entity.getLesson_name();
        if (lesson_name != null) {
            stmt.bindString(2, lesson_name);
        }
 
        Long unit_id = entity.getUnit_id();
        if (unit_id != null) {
            stmt.bindLong(3, unit_id);
        }
 
        Boolean isadd = entity.getIsadd();
        if (isadd != null) {
            stmt.bindLong(4, isadd ? 1L: 0L);
        }
    }

    @Override
    protected void attachEntity(LessonBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LessonBean readEntity(Cursor cursor, int offset) {
        LessonBean entity = new LessonBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // lesson_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // lesson_name
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // unit_id
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // isadd
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LessonBean entity, int offset) {
        entity.setLesson_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLesson_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUnit_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIsadd(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LessonBean entity, long rowId) {
        entity.setLesson_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LessonBean entity) {
        if(entity != null) {
            return entity.getLesson_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUnitBeanDao().getAllColumns());
            builder.append(" FROM LESSON_BEAN T");
            builder.append(" LEFT JOIN UNIT_BEAN T0 ON T.\"UNIT_ID\"=T0.\"UNIT_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LessonBean loadCurrentDeep(Cursor cursor, boolean lock) {
        LessonBean entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        UnitBean unitBean = loadCurrentOther(daoSession.getUnitBeanDao(), cursor, offset);
        entity.setUnitBean(unitBean);

        return entity;    
    }

    public LessonBean loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LessonBean> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LessonBean> list = new ArrayList<LessonBean>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LessonBean> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LessonBean> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
